---
title: "< 12.actividad >"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(datos)
suppressPackageStartupMessages(library(tidyverse))
knitr::opts_chunk$set(echo = TRUE)


# DATOS: Esto se explica mas adelante en el temario
paises07_2VAR <- paises %>% 
 filter(anio==2007)  %>%
 select(pib_per_capita, esperanza_de_vida)

# función describir
#  UTILIZA EL MISMO EJEMPLO DE DESCRIBIR DEL MODULO PARA CREAR UN GRAFICO DE PUNTOS ROJOS A PARTIR DE data
#  HAZ QUE LA FUNCION DEVUELVA el summary de DATA 
describir <- function() {
  plot(pressure)
}

describir()


describir <- function(data, type = "p",  col = 'red', ...) {
  plot(data, type = type, col = col, ...)
  return(summary(data))
}
```

## GRÁFICO DE DISPERSIÓN DE PAÍSES

```{r, fig.cap="Fuente: Elaboración propia con datos de Gapminder", fig.align="center", message=FALSE}

# utiliza la palabra "resumen" para asignar a la función describir creada anteriormente para los datos de paises07_2VAR 
# añade en la función un tipo, un titulo al grafico y también ponle un titulo a los ejes
# nota: añade el concepto en la función de cex.main=1
resumen <- describir(paises07_2VAR
                     , type = "p"
                     , main = "Países (Año: 2007)"
                     , xlab = "PIB per cápita ($ americanos, ajustados según inflación)"
                     , ylab = "Esperanza de vida (años)", cex.main=1)

```

< TABLA DE PAISES >

## TABLA DESCRIPTIVA DE PAÍSES 

```{r}
# utiliza el comando kable para "resumen" y añade un titulo 
kable(resumen, caption = "Resumen (Fuente: Elaboración propia con datos de Gapminder)")
```

< DESCRIBE BREVEMENTE LO QUE OBSERVAS >
